-- ============================================================
-- Repo Rizz — contributors table (Supabase)
--
-- Run with the Supabase CLI:
--   supabase db push
-- or execute this file in the Supabase SQL editor.
--
-- Authorization model:
--   - Public visitors may SELECT (read) contributor rows through the
--     anon key. No INSERT / UPDATE / DELETE policies are granted to
--     anon or authenticated roles, so the public can NEVER mutate
--     contributors directly via the Supabase API.
--   - All writes are performed by the Repo Rizz backend using the
--     service-role key, which bypasses RLS. The backend independently
--     enforces the Rizz Master admin session + CSRF before writing.
-- ============================================================

create table if not exists public.contributors (
    id                bigint generated by default as identity primary key,
    github_username   text not null unique,
    display_name      text not null,
    github_url        text not null,
    role              text not null default '',
    description       text not null default '',
    avatar_url        text not null default '',
    custom_avatar_url text not null default '',
    display_order     integer not null default 0,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

-- Enable Row Level Security: the table is locked down by default.
alter table public.contributors enable row level security;

-- Public read access for everyone (anonymous visitors).
create policy "contributors_public_read"
    on public.contributors
    for select
    to anon, authenticated
    using (true);

-- NOTE: No insert/update/delete policies exist for anon/authenticated.
-- The backend writes through the service-role key only.